[package]
name = "rlu"
version = "0.1.0"
authors = ["Will Crichton <wcrichto@cs.stanford.edu>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
clap = "2.33.0"
bumpalo = "2.6.0"
libc = "0.2.66"
arr_macro = "0.1.3"

[profile.release]
debug = true
